## servlet ##
server:
#  servlet:
#    context-path: /skills
  port: 8888
  tomcat:
    uri-encoding: UTF-8

## database ##
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.0.0.219:5432/clues
    username: saas_user
    password: 123456
  # redis
  redis:
    host: 39.108.49.203
    database: 1
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    password:
    timeout: 1800
  thymeleaf:
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
## mybatis ##
mybatis:
  mapper-locations: mappers/*.xml
  type-aliases-package: wjx.skill.model


#  # dataSource
#  spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
#  spring.datasource.username=root
#  spring.datasource.password=password
#  spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#  spring.datasource.url=jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#
#  #多数据源逗号隔开
#  datasource.names=datasource2,datasource3
#
#  datasource.datasource2.type=com.alibaba.druid.pool.DruidDataSource
#  datasource.datasource2.url=jdbc:mysql://127.0.0.1:3306/test2?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#  datasource.datasource2.driver=com.mysql.jdbc.Driver
#  datasource.datasource2.username=root
#  datasource.datasource2.password=password
#
#
#  datasource.datasource3.type=com.alibaba.druid.pool.DruidDataSource
#  datasource.datasource3.url=jdbc:mysql://127.0.0.1:3306/test3?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#  datasource.datasource3.driver=com.mysql.jdbc.Driver
#  datasource.datasource3.username=root
#  datasource.datasource3.password=password